---
title: Survey Results
author: "R Ladies remote"
date: ""
output: pdf_document
---
  
```{r setup, include=FALSE,echo=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE,results='asis',fig.width=16, fig.height=10)


library(knitr)

library(googlesheets)
library(tidyverse)
library(stringr)
library(kableExtra)
```

```{r}
results <- gs_title("R ladies remote") %>% gs_read

```

There were `r nrow(results)` responses to the R-Ladies remote survey.

```{r}
results = results %>% mutate(country = case_when((tolower(Country) %in% c('us','usa','u.s.a.','south bend'))|grepl('united states',tolower(Country))|(Country=='Georgia'&City=='Atlanta')~'USA',
                                                 grepl('united kingdom|england|scotland|wales|reino unido',tolower(Country))|(tolower(Country)=='uk')~'UK',
                                                 grepl('new zealand|nz',tolower(Country))~'New Zealand',
                                                 grepl('germ|deutschland',tolower(Country))~'Germany',
                                                 grepl('canada|canda',tolower(Country))~'Canada',
                                                 grepl('argenti',tolower(Country))~'Argentina',
                                                 grepl('netherland|holland',tolower(Country))~'Netherlands',
                                                 grepl('colombi',tolower(Country))~'Colombia',
                                                 tolower(Country) %in% c('spain','españa')~'Spain',
                                                 tolower(Country) %in% c('italy','italia')~'Italy',
                                                 tolower(Country) %in% c('norge','norway')~'Norway',
                                                 tolower(Country) %in% c('brazil','brasil')~'Brazil',
                                                 TRUE~str_to_title(Country)))
                             
    
table(results$country) %>% data.frame() %>% arrange(desc(Freq))%>% kable(digits=2)


kable(prop.table(table(results$`What is your current level of R knowledge?`)),digits=2)

#interests = c('Learning R (for those who are new to the language)',
#              'Learning new R skills, in a webinar',
#              'Learning new R skills, paired with one other person or a small group',
#              'Online Office hours about different topics, where you can drop in, as a question, about R, about consultant work, about a certain package, and get some help',
#              'Mentoring for folks at different career stages/experience levels',
#              'Talks about working remotely',
#              'Talks about doing R consulting part or fulltime',
#              'Talks about fighting prejudices (e.g. being a woman, being a mother, wanting to work remotely)',
#              'Resume or portfolio reviews')

results$`Which one(s) below would you be interested in? Select all that apply` = gsub(', ([[:upper:]])','| \\U\\1',results$`Which one(s) below would you be interested in? Select all that apply`,perl=TRUE)
kable(strsplit(results$`Which one(s) below would you be interested in? Select all that apply`,'|',fixed=TRUE) %>% 
  unlist() %>%  trimws()  %>% table() %>% data.frame() %>% mutate(prop = Freq/nrow(results)) %>% arrange(desc(prop)),
  digits=2, format = "latex", booktabs = TRUE) %>%
          kable_styling(latex_options = "scale_down")


results$`Why are you interested in R-Ladies Remote?  (select all applicable)` = gsub(', ([[:upper:]])','| \\U\\1',results$`Why are you interested in R-Ladies Remote?  (select all applicable)`,perl=TRUE)
kable(strsplit(results$`Why are you interested in R-Ladies Remote?  (select all applicable)`,'|',fixed=TRUE) %>% 
        unlist() %>%  trimws() %>% table() %>% data.frame() %>% mutate(prop = Freq/nrow(results)) %>% arrange(desc(prop)),digits=2, format = "latex", booktabs = TRUE) %>%
          kable_styling(latex_options = "scale_down")

```